language: java
jdk:
- openjdk11
before_cache:
  - rm -rf $HOME/.m2/repository/com/autentia/traviscodacy

before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

after_success:
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r users-api/build/reports/jacoco/test/jacocoTestReport.xml

deploy:
  skip_cleanup: false
  provider: heroku
  api_key:
    secure: $HEROKU
  app: bbooks-api

