language: java
sudo: required
before_install:
  - curl -sL http://bit.ly/jpm4j >jpm4j.jar
  - sudo java -jar jpm4j.jar -g init
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
after_success:
  - codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml  --p
jdk:
- openjdk11
deploy:
  skip_cleanup: false
  provider: heroku
  api_key:
    secure: $HEROKU
  app: bbooks-api

