server:
  port: 8082
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./api-competition-development
    username: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  jpa:
    open-in-view: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update