spring:
  profiles:
    active: "staging"
  datasource:
    driverClassName: org.postgresql.Driver
    url: $JDBC_DATABASE_URL
    username: $JDBC_DATABASE_USERNAME
    password: $JDBC_DATABASE_PASSWORD
  jpa:
    generate-ddl: true
#    database: postgresql
    databasePlatform: "org.hibernate.dialect.PostgreSQL9Dialect"
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  mail:
    host: smtp.gmail.com
    username: $EMAIL_USERNAME
    password: $EMAIL_PASSWORD
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
#logging:
#  level:
#    org.springframework: ERROR
#    se.some.url: DEBUG:
#  file:
#    name: app.log
#
#  level.org.springframework=ERROR
#  logging.level.br.edu.ifsp.spo.bulls.usersApi=DEBUG
#
#  output to a file
#  logging.file.name=app.log
#
#  temp folder example
#  logging.file=${java.io.tmpdir}/app.log
#
#  logging.pattern.file=%d %p %c{1.} [%t] %m%n
#  logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
#
#  # if no active profile, default is 'default'
#  #spring.profiles.active=prod
#
#  root level
#  logging.level.=INFO