server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: $JDBC_DATABASE_URL
    username: $JDBC_DATABASE_USERNAME
    password: $JDBC_DATABASE_PASSWORD
  jpa:
    generate-ddl: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: $EMAIL_USERNAME
    password: $EMAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true