server:
  port: 8081
feign:
  users: ${USERS_API}
  competition: ${COMPETITION_API:'localhost:8082'}
spring:
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    driverClassName: org.postgresql.Driver
    url: $JDBC_DATABASE_URL
    username: $JDBC_DATABASE_USERNAME
    password: $JDBC_DATABASE_PASSWORD
    max-active: 6
  jpa:
    generate-ddl: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    debug: true
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
heroku:
  enforceHttps: true