name: Java CI with Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit tests
        run: |
          sudo apt-get install jq
          curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar
          ./gradlew test
      - name: Build with Gradle
        run: ./gradlew build
#      - name: Deploy to Heroku
#        env:
#          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
#          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
#        if: github.ref == 'refs/heads/master' && job.status == 'success'
#        run: |
#          git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
#          git push heroku HEAD:master -f
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: users-api/build/reports/jacoco/test/jacocoTestReport.xml